name = "OscillatingHeatPipe"
uuid = "d0e5c285-36a4-4c17-b2d2-a3652d369245"
authors = ["yuxuanli <liyuxuan48@live.com>"]
version = "0.1.0"

[deps]
CartesianGrids = "3e975e5d-2cf8-4263-9573-8460aaf534d9"
ComputationalHeatTransfer = "5fc296c8-2eb5-40dc-a46d-98a68011a900"
ConstrainedSystems = "c257ce95-4918-4279-a47c-50fdbcb74a04"
CoolProp = "e084ae63-2819-5025-826e-f8e611a84251"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EasyFit = "fde71243-0cda-4261-b7c7-4845bd106b21"
GridUtilities = "5c019650-0847-4ff6-8f91-f8ecfc8c3009"
ImmersedLayers = "cdc13194-334e-4e1c-bc8d-fc3a28509c85"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RigidBodyTools = "befc5f09-81d5-499c-a4b2-d0464ba9f9c8"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CartesianGrids = "0.1.29, 0.1.30"
ConstrainedSystems = "0.3.6, 0.3.6"
DocStringExtensions = "0.8.1, 0.9"
LinearAlgebra = "1.6"
Plots = "1.35, 1.36, 1.37, 1.38"
RecipesBase = "1.0"
Reexport = "0.2.0, 1.0"
UnPack = "1.0"
julia = "1.6"
